spring.application.name=terza-app-spring-H2

# Porta del server
# In questo modo imposta la porta sul quale Tomcat comunica
server.port=8080

# H2 in memoria
#Specifica la connessione dal DB in memoria (si cancella al riavvio)
#:studentedb è il nome del db disponibile (perfetto per i test/dimostrazioni, non per produzione)
#ATT: spring genera un UUID che devo andare a prendere dal terminale per poterlo utilizzare in console
spring.datasource.url=jdbc:h2:file:./target/h2db/studentdb
#Indica la classe del Driver 
spring.datasource.driverClassName=org.h2.Driver
#sa è il Super Admin e la pass è vuota. Ovviamente in produzione bisogna usare pass forti
spring.datasource.username=sa
spring.datasource.password=

# Console H2 - Questa è la console web accessibile da http://localhost:8080/h2-console
# Accedere alla console solo quando hai già creato le entities
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate - Configurazione per la strategia di creazione e aggiornamento automatico delle tabelle del DB
# il Valore update è il migliore per lo sviluppo perché crea/aggiorna le tabelle in automatico. Esistono anche altri
# valori come "create" (cancella e ricrea tutto), "create-drop"(crea e cancella al riavvio),
# "validate" (solo verifica)
spring.jpa.hibernate.ddl-auto=update

#Mostra le query in console
spring.jpa.show-sql=true

#Formatta le sql nei log
spring.jpa.properties.hibernate.format_sql=true
#Specifica il Dialect Hibernate per H2. In dettaglio: traduce le query JPA/HQL in SQL specifico per H2.
#SpringBoot è in grado di rilevarlo automaticamente ma è meglio specificarlo
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# Debug
logging.level.org.hibernate.SQL=DEBUG
